CREATE TABLE adm (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role VARCHAR(10) DEFAULT 'ADM',
    user_id BIGINT NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY  (user_id) REFERENCES users(id) ON DELETE CASCADE

)